# Use H2 in-memory database
spring.datasource.url=jdbc:h2:file:./data/clinicdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Hibernate / JPA settings (Auto-creates tables based on our code)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable H2 web console to view the database in your browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logging Configuration
logging.file.name=logs/DoctorBooking.log
logging.level.root=INFO

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=blrrudresh972@gmail.com
# Use a Google "App Password" here, NOT your regular login password
spring.mail.password=bjvkzeslsfrvkacq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Custom property for notifications
clinic.owner.email=bhuvis459@gmail.com
