spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/doctor_booking_local}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:Bhuvana@2026}

# Hibernate / JPA settings (Auto-creates tables based on our code)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging Configuration
logging.file.name=logs/DoctorBooking.log
logging.level.root=INFO

# Mail Configuration
spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME:blrrudresh972@gmail.com}
# Use a Google "App Password" here, NOT your regular login password
spring.mail.password=${SMTP_PASSWORD:bjvkzeslsfrvkacq}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# External Service Configurations
whatsapp.api.url=${WHATSAPP_API_URL:http://localhost:3000}
business.email=${BUSINESS_EMAIL:blrrudresh972@gmail.com}
lab.owner.email=${LAB_OWNER_EMAIL:bhuvis459@gmail.com}
lab.owner.whatsapp=${LAB_OWNER_WHATSAPP_NUMBER:919876543210}
